#!/bin/bash
# Quick Start Reference - AI-Driven SaaS Firewall
# Usage: Run these commands in order to deploy the firewall

set -e

echo "╔════════════════════════════════════════════════════════════════════════════════╗"
echo "║      AI-Driven Autonomous and Adaptive Firewall - SaaS Upgrade v2025.1        ║"
echo "╚════════════════════════════════════════════════════════════════════════════════╝"
echo ""

# Color codes
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

echo -e "${BLUE}PHASE 1: TRAIN ML MODELS${NC}"
echo "────────────────────────────────────────────────────────────────────────────────"
echo "This step trains the CNN and Random Forest models for threat detection"
echo ""
echo -e "${YELLOW}Command:${NC}"
echo "  cd ml-engine"
echo "  python ml_train/train_manager.py --mode all"
echo ""
echo -e "${YELLOW}Options:${NC}"
echo "  --mode waf      Train only SQL Injection detector (CNN)"
echo "  --mode nids     Train only DDoS detector (Random Forest)"
echo "  --mode all      Train both models (default)"
echo ""
echo -e "${YELLOW}Output:${NC}"
echo "  ml-engine/models/"
echo "  ├── waf_cnn.h5          (CNN model for SQL Injection)"
echo "  ├── tokenizer.pkl       (Text tokenizer)"
echo "  ├── nids_rf.pkl         (Random Forest model)"
echo "  └── scaler.pkl          (Feature scaler)"
echo ""

echo -e "${BLUE}PHASE 2: CONFIGURE NETWORK (3-VM DEMO)${NC}"
echo "────────────────────────────────────────────────────────────────────────────────"
echo "Setup IP forwarding, NAT, and firewall rules on gateway VM"
echo ""
echo -e "${YELLOW}Command:${NC}"
echo "  sudo bash agent/setup_demo_network.sh"
echo ""
echo -e "${YELLOW}What it does:${NC}"
echo "  ✓ Enable IPv4 forwarding"
echo "  ✓ Create NAT rules (Masquerade)"
echo "  ✓ Create ipset blacklist"
echo "  ✓ Configure iptables rules"
echo ""

echo -e "${BLUE}PHASE 3: START DASHBOARD API${NC}"
echo "────────────────────────────────────────────────────────────────────────────────"
echo "Launch the FastAPI dashboard for alert aggregation"
echo ""
echo -e "${YELLOW}Command:${NC}"
echo "  cd dashboard-api"
echo "  python -m uvicorn app.main:app --host 0.0.0.0 --port 8000"
echo ""
echo -e "${YELLOW}Access dashboard:${NC}"
echo "  http://localhost:8000"
echo ""
echo -e "${YELLOW}Test with curl:${NC}"
echo "  curl http://localhost:8000/alerts/stats"
echo ""

echo -e "${BLUE}PHASE 4: START SAAS ENFORCER AGENT${NC}"
echo "────────────────────────────────────────────────────────────────────────────────"
echo "Launch real-time packet sniffer with threat detection"
echo ""
echo -e "${YELLOW}Local Mode (protect firewall host):${NC}"
echo "  sudo python agent/saas_enforcer.py --mode local"
echo ""
echo -e "${YELLOW}Gateway Mode (protect victim VM):${NC}"
echo "  sudo python agent/saas_enforcer.py --mode gateway --target-ip 192.168.1.10"
echo ""
echo -e "${YELLOW}With custom dashboard URL:${NC}"
echo "  sudo python agent/saas_enforcer.py \\"
echo "    --mode gateway \\"
echo "    --target-ip 192.168.1.10 \\"
echo "    --dashboard-url http://192.168.1.50:8000"
echo ""

echo -e "${BLUE}MONITORING & DIAGNOSTICS${NC}"
echo "────────────────────────────────────────────────────────────────────────────────"
echo ""
echo -e "${YELLOW}View real-time alerts:${NC}"
echo "  curl http://localhost:8000/alerts?limit=20"
echo ""
echo -e "${YELLOW}Get attack statistics:${NC}"
echo "  curl http://localhost:8000/alerts/stats"
echo ""
echo -e "${YELLOW}View persistent alert log:${NC}"
echo "  tail -f logs/alerts.jsonl"
echo ""
echo -e "${YELLOW}Check blocked IPs:${NC}"
echo "  sudo ipset list blacklist"
echo ""
echo -e "${YELLOW}View iptables rules:${NC}"
echo "  sudo iptables -L -n"
echo ""

echo -e "${BLUE}PYTHON API USAGE${NC}"
echo "────────────────────────────────────────────────────────────────────────────────"
echo ""
echo "# Use firewall controller programmatically"
echo "from agent.controls.firewall_controller import FirewallController"
echo ""
echo "controller = FirewallController()"
echo ""
echo "# Block malicious IPs"
echo "controller.block_ip('192.168.1.100', timeout=1800)"
echo ""
echo "# Whitelist trusted IPs"
echo "controller.whitelist_ip('10.0.0.1', permanent=True)"
echo ""
echo "# Check status"
echo "print('Blocked IPs:', controller.get_blocked_ips())"
echo "print('Whitelisted IPs:', controller.get_whitelisted_ips())"
echo ""

echo -e "${BLUE}DEPLOYMENT CHECKLIST${NC}"
echo "────────────────────────────────────────────────────────────────────────────────"
echo ""
echo "Before production deployment, verify:"
echo ""
echo "  [ ] Models trained: ls ml-engine/models/"
echo "  [ ] Network configured: cat /proc/sys/net/ipv4/ip_forward"
echo "  [ ] Dashboard running: curl http://localhost:8000/alerts/stats"
echo "  [ ] Enforcer running: ps aux | grep saas_enforcer"
echo "  [ ] Permissions set: ls -la agent/*.sh agent/*.py"
echo "  [ ] ipset installed: which ipset"
echo "  [ ] iptables rules: sudo iptables -L -n"
echo "  [ ] Log directory writable: touch logs/test.log"
echo ""

echo -e "${YELLOW}Documentation:${NC}"
echo "  Full guide: SAAS_UPGRADE_COMPLETE.md"
echo ""

echo -e "${GREEN}════════════════════════════════════════════════════════════════════════════════${NC}"
echo -e "${GREEN}Ready to deploy? Start with Phase 1 above!${NC}"
echo -e "${GREEN}════════════════════════════════════════════════════════════════════════════════${NC}"
